version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
          time: "21:00"
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: cssnano
            versions:
                - 5.0.0
                - 5.0.1
          - dependency-name: tailwindcss
            versions:
                - 2.1.0
          - dependency-name: gscan
            versions:
                - 4.0.0
          - dependency-name: husky
            versions:
                - 5.1.2
          - dependency-name: postcss
            versions:
                - 8.2.5
