name: Test and Deploy Theme
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo '::set-output name=dir::$(yarn cache dir)'
      - name: Cache Yarn
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install yarn
      - run: yarn install
      - run: yarn test:ci
      - run: yarn zip

      - name: Deploy theme
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: node scripts/deploy_theme.js
        env:
          url: ${{ secrets.GHOST_API_URL }}
          key: ${{ secrets.GHOST_DEPLOY_THEME_ADMIN_API_KEY }}
          path: 'dist/ghost-advisory-theme.zip'
